### ISSUE TITLE
İlgisiz Metinleri Çıkarma

### ISSUE THREAD

**Issue by yemregundogmus** [acikkaynak/deprem-yardim-address-api#26]
Ekteki gibi ilgisiz verileri elemek için adress resolver pipeline'ına özel bir regex yazılabilir mi? 

cc- #ai

![](https://media.discordapp.net/attachments/1073648059105415208/1073974979856711819/image.png?width=1857&height=910)

**Comment by merveenoyan** [comment]
Dönen JSON response'ta Alakasız label'ı varsa ve score 0.5'in üstündeyse atabiliriz cc @mstrYoda @hmert

**Comment by flower-gardener** [comment]
"emlak" icin regex yazip filtreleyebiliriz

**Comment by mstrYoda** [comment]
> Dönen JSON response'ta Alakasız label'ı varsa ve score 0.5'in üstündeyse atabiliriz cc @mstrYoda @hmert 

Alakasız score'unu arttırıp yayına alacağım. @merveenoyan mevcut alakasızların bir üzerinden geçip modele beslemek faydalı olabilir göndereceğim bu veriyi size
